version: "3"

services:
  nats-server:
    image: nats:2.10.22-alpine3.20

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    environment:
      - APP_PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms
    environment:
      - APP_PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  # pgdb-orders-ms:
  #   container_name: pg_orders_database
  #   image: postgres:17.0-alpine
  #   restart: always
  #   volumes:
  #     - ./orders-ms/postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=orders

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DB_URL=${ORDERS_DB_URL}
    image: orders-ms
    environment:
      - APP_PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DB_URL}

  payments-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - APP_PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms
    environment:
      - APP_PORT=${AUTH_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=superSecret
      - JWT_ISSUER=auth.ms
      - JWT_EXPIRES=12h